### ISSUE TITLE
Paring Issue

### ISSUE THREAD

**Issue by roberttaggart** [damageless/MyoTaskerPlugin#2]
The plugin is not connecting to my Myo.  
I have a Samsung S5.  I placed the Myo to the phone and waited for 'Myo connected'. I also tapped 'Connect to Myo' on the bottom.  I have uninstalled and reinstalled multiple times.  Is there anything else I can do?

**Comment by damageless** [comment]
Have you updated your Myo to the latest firmware?

**Comment by damageless** [comment]
roberttaggart, were you able to resolve your issue?

**Comment by roberttaggart** [comment]
Yes thankyou ver much.

**Comment by jeremytwfortune** [comment]
I have a Verizon LG G3 on Android 4.4.2 with Myo firmware version 1.1.5 and have been unable to pair with my phone. I've tried wearing and not wearing the device.
